# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c11d9f1d8d0aad17a81c93618bd2fc4b29919f527fda8aaee669c8bdabe7eb9d79cc71038118356ca410bd34d424e9f6bdee1f91038ece4f5d67fb65b14f763

test:
  secret_key_base: 0f42d89e9826f5df34664e362bc4df9a64c8042edbf1fcb42edd609c9b7544081019bf7df7a89cef2abb856274dbf4a41ba0fb0549c2e9f73dfb67c548aec867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
